name: Lint

on:
    workflow_call: # Add this to make it reusable
      inputs:
        python-version:
          description: "Python version to use"
          type: string
          required: false
          default: "3.12"
    push:
      branches: [ main ]
    pull_request:
      branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          
      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          
      - name: Install dependencies
        run: poetry install
        
      - name: Run Black
        run: poetry run black . --check
        
      # Optional: Fail if formatting is needed
      - name: Check if changes were needed
        if: failure()
        run: |
          echo "::error::Black formatting check failed. Please run 'black .' locally and commit the changes."
          exit 1