name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  lint:
    uses: ./.github/workflows/lint.yml

  release:
    needs: lint  # This ensures lint job passes before creating release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          
      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          
      - name: Build package
        run: poetry build
        
      - name: Publish to PyPI
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{secrets.GITHUB_PYPI_API_TOKEN}}
        run: |
          poetry publish
        
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/*.whl
            dist/*.tar.gz
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_ACTIONS_TOKEN }}
